export const PHOTOSHOOT_STYLES = [
  "Haji / Umroh",
  "Studio Berwarna",
  "Akad Nikah",
  "Resepsi Pernikahan",
  "Pre-Wedding Outdoor",
  "Pre-Wedding Indoor",
  "Pas Foto Formal (Merah/Biru)",
  "Foto Ijazah / Sekolah",
  "Wisuda (Graduation)",
  "Corporate / Professional Headshot",
  "Casual Studio",
  "Vintage / Retro 90s",
  "Cinematic Moody",
  "Neon Cyberpunk",
  "Glamour / Fashion Editorial",
  "Maternity (Ibu Hamil)",
  "Family Portrait",
  "Newborn / Bayi",
  "Pakaian Adat Tradisional",
  "Fine Art Portrait",
  "Black and White Classic",
  "Street Photography Style",
  "Ethereal / Fairy Tale",
  "Sporty / Athletic",
  "Minimalist White",
  "Dark Academia",
  "Light Academia",
  "Y2K / 2000s Pop",
  "Futuristic / Sci-Fi",
  "Royal / Kerajaan",
  "Idul Fitri / Lebaran"
];

export const MODES = [
  {
    id: 'imajinasi',
    name: 'Mode Imajinasi',
    icon: 'Sparkles',
    description: 'Buat gambar baru dari teks imajinasi Anda',
    requiredFields: ['prompt', 'aspectRatio'],
    optionalFields: [],
  },
  {
    id: 'pose',
    name: 'Mode Pose',
    icon: 'PersonStanding',
    description: 'Ubah pose model mengikuti referensi',
    requiredFields: ['image'],
    optionalFields: ['poseImage', 'prompt'],
  },
  {
    id: 'edit',
    name: 'Mode Edit Foto',
    icon: 'Wand2',
    description: 'Edit gambar tanpa mengubah background/posisi',
    requiredFields: ['image', 'prompt'],
    optionalFields: [],
  },
  {
    id: 'product',
    name: 'Mode Produk',
    icon: 'Package',
    description: 'Foto katalog produk profesional',
    requiredFields: ['image'],
    optionalFields: ['modelImages', 'prompt'],
  },
  {
    id: 'thumbnail',
    name: 'Mode Thumbnail',
    icon: 'Youtube',
    description: 'Desain clickbait menarik',
    requiredFields: ['image', 'title'],
    optionalFields: ['subtitle', 'prompt'],
  },
  {
    id: 'poster',
    name: 'Mode Poster',
    icon: 'Image',
    description: 'Poster promosi',
    requiredFields: ['image', 'title', 'subtitle'],
    optionalFields: ['prompt'],
  },
  {
    id: 'photoshoot',
    name: 'Mode Photoshoot',
    icon: 'Camera',
    description: 'Ubah jadi foto studio dengan 31 pilihan gaya',
    requiredFields: ['image', 'photoshootStyle'],
    optionalFields: ['prompt', 'photoshootColor'],
  },
  {
    id: 'logo',
    name: 'Mode Buat Logo',
    icon: 'Hexagon',
    description: 'Buat logo profesional',
    requiredFields: ['brandName', 'tagline'],
    optionalFields: ['image', 'prompt'],
  },
  {
    id: 'busana',
    name: 'Mode Coba Busana',
    icon: 'Shirt',
    description: 'Coba busana tanpa ubah tubuh/posisi',
    requiredFields: ['image', 'clothingImages'],
    optionalFields: ['prompt'],
  },
  {
    id: 'mix',
    name: 'Mode Mix Foto',
    icon: 'Layers',
    description: 'Gabungkan maksimal 6 foto',
    requiredFields: ['mixImages'],
    optionalFields: ['prompt'],
  },
];
